create table
  public.global_inventory (
    id integer generated by DEFAULT AS identity,
    num_red_potions integer null DEFAULT 0,
    num_red_ml integer null DEFAULT 0,
    num_green_potions integer not null DEFAULT 0,
    num_green_ml integer null DEFAULT 0,
    num_blue_potions integer null DEFAULT 0,
    num_blue_ml integer null DEFAULT 0,
    num_purple_potions integer null DEFAULT 0,
    num_purple_ml integer null DEFAULT 0,
    gold integer null DEFAULT 0,
    constraint globInvenPrimKey PRIMARY KEY (id)
  ) TABLESPACE pg_default;

create table
  public.carts_table (
    cart_id integer generated by DEFAULT AS identity,
    customer_name text null DEFAULT 'noName'::text,
    constraint cartsPrimKey PRIMARY KEY (cart_id),
    constraint cartsIdKey UNIQUE (cart_id)
  ) TABLESPACE pg_default;

create table
  public.potionOfferings (
    potID integer generated by DEFAULT AS identity,
    potName text null DEFAULT 'noName'::text,
    redPot integer null DEFAULT 0,
    greenPot integer null DEFAULT 0,
    bluePot integer null DEFAULT 0,
    blackPot integer null DEFAULT 0,
    price integer null DEFAULT 0,
    quantSelling integer null DEFAULT 0,
    constraint potionOffsPKey PRIMARY KEY (potID)
  ) TABLESPACE pg_default;
  
create table
  public.cart_items (
    cart_id_cust integer generated by DEFAULT AS identity,
    amount integer null DEFAULT 0,
    pot_type integer null,
    constraint cart_items_pkey PRIMARY KEY (cart_id_cust),
    constraint cartItemsCustIdForKey FOREIGN KEY (cart_id_cust) REFERENCES carts_table (cart_id),
    constraint cartItemsPotIdForKey FOREIGN KEY (pot_type) REFERENCES potionOfferings (potID)
  ) TABLESPACE pg_default;